import jsPDF from 'jspdf';
import type { PnLReport, PnLCategory } from '../types';

// Colors
const NAVY = [26, 58, 92] as const;
const GREEN = [22, 163, 74] as const;
const RED = [220, 38, 38] as const;
const GREY = [107, 114, 128] as const;
const LGREY = [228, 231, 236] as const;
const SURFACE = [249, 250, 251] as const;
const LBLUE = [239, 246, 255] as const;
const WHITE = [255, 255, 255] as const;
const DARK = [61, 61, 61] as const;

const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;
const MARGIN = 48;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

function formatCurrency(value: number): string {
  const abs = Math.abs(value).toLocaleString('en-US', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
  return value < 0 ? `($${abs})` : `$${abs}`;
}

export function generatePDF(report: PnLReport): string | null {
  try {
    const doc = new jsPDF({ unit: 'pt', format: 'letter' });
    let y = 0;
    let currentPage = 1;

    const rightEdge = PAGE_WIDTH - MARGIN;

    function checkPageBreak(needed: number) {
      if (y > PAGE_HEIGHT - MARGIN - needed) {
        // Footer on current page
        drawFooter();
        doc.addPage();
        currentPage++;
        y = MARGIN;
      }
    }

    function drawFooter() {
      const dateStr = new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      });
      // Separator line
      doc.setDrawColor(...LGREY);
      doc.setLineWidth(0.3);
      doc.line(MARGIN, PAGE_HEIGHT - MARGIN + 4, rightEdge, PAGE_HEIGHT - MARGIN + 4);
      // Left text
      doc.setFontSize(7.5);
      doc.setTextColor(...GREY);
      doc.text(`Generated by BookkeepingAI  ${dateStr}`, MARGIN, PAGE_HEIGHT - MARGIN + 18);
      // Page number
      const pageText = `Page ${currentPage}`;
      const pw = doc.getTextWidth(pageText);
      doc.text(pageText, rightEdge - pw, PAGE_HEIGHT - MARGIN + 18);
    }

    // --- Header ---
    y = 0;
    // Calculate header height based on available business info
    const hasAddress = report.businessAddress && report.businessAddress.trim();
    const hasPhone = report.businessPhone && report.businessPhone.trim();
    const headerHeight = 72 + (hasAddress ? 14 : 0) + (hasPhone ? 14 : 0);

    doc.setFillColor(...NAVY);
    doc.rect(0, 0, PAGE_WIDTH, headerHeight, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(20);
    doc.setTextColor(...WHITE);
    doc.text(report.businessName ?? 'My Business', MARGIN, 34);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.text('Profit & Loss Statement', MARGIN, 52);

    let headerY = 66;
    doc.setFontSize(9);
    doc.setTextColor(204, 204, 204);
    doc.text(report.period ?? '', MARGIN, headerY);

    if (hasAddress) {
      headerY += 14;
      doc.setFontSize(8.5);
      doc.text(report.businessAddress!, MARGIN, headerY);
    }

    if (hasPhone) {
      headerY += 14;
      doc.setFontSize(8.5);
      doc.text(report.businessPhone!, MARGIN, headerY);
    }

    y = headerHeight + 18;

    // --- Summary Cards ---
    const totalExpenses = (report.totalCOGS ?? 0) + (report.totalOpex ?? 0);
    const netIncome = report.netIncome ?? 0;
    const hasTaxSplit = (report.totalTaxableCOGS != null) || (report.totalNonTaxableCOGS != null);
    const cardCount = hasTaxSplit ? 5 : 3;
    const cardWidth = (CONTENT_WIDTH - 8 * (cardCount - 1)) / cardCount;
    const cardHeight = 52;

    const cards: Array<{ label: string; value: number; color: readonly [number, number, number] }> = [
      { label: 'TOTAL REVENUE', value: report.totalRevenue ?? 0, color: GREEN },
      ...(hasTaxSplit ? [
        { label: 'TAXABLE COGS', value: report.totalTaxableCOGS ?? 0, color: RED as readonly [number, number, number] },
        { label: 'NON-TAX COGS', value: report.totalNonTaxableCOGS ?? 0, color: GREEN as readonly [number, number, number] },
      ] : []),
      { label: 'TOTAL EXPENSES', value: totalExpenses, color: RED },
      { label: 'NET INCOME', value: netIncome, color: netIncome >= 0 ? GREEN : RED },
    ];

    cards.forEach((card, i) => {
      const x = MARGIN + i * (cardWidth + 8);
      // Card background
      doc.setFillColor(...SURFACE);
      doc.setDrawColor(...LGREY);
      doc.setLineWidth(0.5);
      doc.roundedRect(x, y, cardWidth, cardHeight, 4, 4, 'FD');

      // Label
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(hasTaxSplit ? 6.5 : 7.5);
      doc.setTextColor(...GREY);
      doc.text(card.label, x + 6, y + 18);

      // Value
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(hasTaxSplit ? 11 : 14);
      doc.setTextColor(...card.color);
      doc.text(formatCurrency(card.value), x + 6, y + 40);
    });

    y += cardHeight + 16;

    // --- Section Renderer ---
    function drawSection(
      title: string,
      categories: PnLCategory[],
      totalLabel: string,
      totalValue: number
    ) {
      checkPageBreak(40);

      // Section title bar
      doc.setFillColor(...NAVY);
      doc.rect(MARGIN, y, CONTENT_WIDTH, 18, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(...WHITE);
      doc.text(title, MARGIN + 8, y + 13);
      y += 22;

      for (const cat of categories) {
        checkPageBreak(30);

        const catTotal = (cat.items ?? []).reduce((sum, it) => sum + (it.amount ?? 0), 0);

        // Category header
        doc.setFillColor(232, 240, 247);
        doc.rect(MARGIN, y, CONTENT_WIDTH, 16, 'F');
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8.5);
        doc.setTextColor(...NAVY);
        doc.text(cat.category, MARGIN + 8, y + 12);

        const catValStr = formatCurrency(catTotal);
        const catValW = doc.getTextWidth(catValStr);
        doc.text(catValStr, rightEdge - catValW, y + 12);
        y += 18;

        // Line items
        (cat.items ?? []).forEach((item, idx) => {
          checkPageBreak(16);

          if (idx % 2 === 0) {
            doc.setFillColor(249, 249, 249);
            doc.rect(MARGIN, y, CONTENT_WIDTH, 14, 'F');
          }

          const desc = item.description ?? '';
          const truncated = desc.length > 60 ? desc.substring(0, 57) + '...' : desc;
          const lineText = `  ${item.date ?? ''}  ${truncated}`;

          doc.setFont('helvetica', 'normal');
          doc.setFontSize(8);
          doc.setTextColor(...DARK);
          doc.text(lineText, MARGIN + 4, y + 10);

          const amtStr = formatCurrency(item.amount ?? 0);
          const amtW = doc.getTextWidth(amtStr);
          doc.text(amtStr, rightEdge - amtW, y + 10);

          y += 14;
        });

        // Separator
        doc.setDrawColor(...LGREY);
        doc.setLineWidth(0.3);
        doc.line(MARGIN, y, rightEdge, y);
        y += 4;
      }

      checkPageBreak(22);

      // Section total
      doc.setFillColor(...NAVY);
      doc.rect(MARGIN, y, CONTENT_WIDTH, 18, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(...WHITE);
      doc.text(totalLabel, MARGIN + 8, y + 13);

      const totalValStr = formatCurrency(totalValue);
      const totalValW = doc.getTextWidth(totalValStr);
      doc.text(totalValStr, rightEdge - totalValW, y + 13);
      y += 26;
    }

    // --- Revenue ---
    if (report.revenue && report.revenue.length > 0) {
      drawSection('REVENUE', report.revenue, 'Total Revenue', report.totalRevenue ?? 0);
    }

    // --- COGS ---
    const hasTaxableSplit = (report.taxableCOGS && report.taxableCOGS.length > 0) ||
                            (report.nonTaxableCOGS && report.nonTaxableCOGS.length > 0) ||
                            (report.mixedCOGS && report.mixedCOGS.length > 0);

    if (hasTaxableSplit) {
      // Section title bar for COGS parent
      checkPageBreak(40);
      doc.setFillColor(...NAVY);
      doc.rect(MARGIN, y, CONTENT_WIDTH, 18, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(...WHITE);
      doc.text('COST OF GOODS SOLD', MARGIN + 8, y + 13);
      y += 22;

      // Taxable COGS subsection
      if (report.taxableCOGS && report.taxableCOGS.length > 0) {
        checkPageBreak(24);
        doc.setFillColor(254, 226, 226); // light red tint
        doc.rect(MARGIN, y, CONTENT_WIDTH, 16, 'F');
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8.5);
        doc.setTextColor(185, 28, 28);
        doc.text('TAXABLE COGS', MARGIN + 8, y + 12);
        y += 18;

        for (const cat of report.taxableCOGS) {
          checkPageBreak(30);
          const catTotal = (cat.items ?? []).reduce((sum, it) => sum + (it.amount ?? 0), 0);

          doc.setFillColor(232, 240, 247);
          doc.rect(MARGIN, y, CONTENT_WIDTH, 16, 'F');
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(8.5);
          doc.setTextColor(...NAVY);
          doc.text(cat.category, MARGIN + 8, y + 12);
          const catValStr = formatCurrency(catTotal);
          const catValW = doc.getTextWidth(catValStr);
          doc.text(catValStr, rightEdge - catValW, y + 12);
          y += 18;

          (cat.items ?? []).forEach((item, idx) => {
            checkPageBreak(16);
            if (idx % 2 === 0) {
              doc.setFillColor(249, 249, 249);
              doc.rect(MARGIN, y, CONTENT_WIDTH, 14, 'F');
            }
            const desc = item.description ?? '';
            const truncated = desc.length > 60 ? desc.substring(0, 57) + '...' : desc;
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(8);
            doc.setTextColor(...DARK);
            doc.text(`  ${item.date ?? ''}  ${truncated}`, MARGIN + 4, y + 10);
            const amtStr = formatCurrency(item.amount ?? 0);
            const amtW = doc.getTextWidth(amtStr);
            doc.text(amtStr, rightEdge - amtW, y + 10);
            y += 14;
          });

          doc.setDrawColor(...LGREY);
          doc.setLineWidth(0.3);
          doc.line(MARGIN, y, rightEdge, y);
          y += 4;
        }

        // Taxable COGS subtotal
        checkPageBreak(18);
        doc.setFillColor(254, 226, 226);
        doc.rect(MARGIN, y, CONTENT_WIDTH, 16, 'F');
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8.5);
        doc.setTextColor(185, 28, 28);
        doc.text('Taxable COGS Subtotal', MARGIN + 8, y + 12);
        const taxSubStr = formatCurrency(report.totalTaxableCOGS ?? 0);
        const taxSubW = doc.getTextWidth(taxSubStr);
        doc.text(taxSubStr, rightEdge - taxSubW, y + 12);
        y += 22;
      }

      // Non-Taxable COGS subsection
      if (report.nonTaxableCOGS && report.nonTaxableCOGS.length > 0) {
        checkPageBreak(24);
        doc.setFillColor(220, 252, 231); // light green tint
        doc.rect(MARGIN, y, CONTENT_WIDTH, 16, 'F');
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8.5);
        doc.setTextColor(21, 128, 61);
        doc.text('NON-TAXABLE COGS', MARGIN + 8, y + 12);
        y += 18;

        for (const cat of report.nonTaxableCOGS) {
          checkPageBreak(30);
          const catTotal = (cat.items ?? []).reduce((sum, it) => sum + (it.amount ?? 0), 0);

          doc.setFillColor(232, 240, 247);
          doc.rect(MARGIN, y, CONTENT_WIDTH, 16, 'F');
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(8.5);
          doc.setTextColor(...NAVY);
          doc.text(cat.category, MARGIN + 8, y + 12);
          const catValStr = formatCurrency(catTotal);
          const catValW = doc.getTextWidth(catValStr);
          doc.text(catValStr, rightEdge - catValW, y + 12);
          y += 18;

          (cat.items ?? []).forEach((item, idx) => {
            checkPageBreak(16);
            if (idx % 2 === 0) {
              doc.setFillColor(249, 249, 249);
              doc.rect(MARGIN, y, CONTENT_WIDTH, 14, 'F');
            }
            const desc = item.description ?? '';
            const truncated = desc.length > 60 ? desc.substring(0, 57) + '...' : desc;
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(8);
            doc.setTextColor(...DARK);
            doc.text(`  ${item.date ?? ''}  ${truncated}`, MARGIN + 4, y + 10);
            const amtStr = formatCurrency(item.amount ?? 0);
            const amtW = doc.getTextWidth(amtStr);
            doc.text(amtStr, rightEdge - amtW, y + 10);
            y += 14;
          });

          doc.setDrawColor(...LGREY);
          doc.setLineWidth(0.3);
          doc.line(MARGIN, y, rightEdge, y);
          y += 4;
        }

        // Non-Taxable COGS subtotal
        checkPageBreak(18);
        doc.setFillColor(220, 252, 231);
        doc.rect(MARGIN, y, CONTENT_WIDTH, 16, 'F');
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8.5);
        doc.setTextColor(21, 128, 61);
        doc.text('Non-Taxable COGS Subtotal', MARGIN + 8, y + 12);
        const ntSubStr = formatCurrency(report.totalNonTaxableCOGS ?? 0);
        const ntSubW = doc.getTextWidth(ntSubStr);
        doc.text(ntSubStr, rightEdge - ntSubW, y + 12);
        y += 22;
      }

      // Mixed COGS subsection
      if (report.mixedCOGS && report.mixedCOGS.length > 0) {
        checkPageBreak(24);
        doc.setFillColor(255, 243, 224); // light orange tint
        doc.rect(MARGIN, y, CONTENT_WIDTH, 16, 'F');
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8.5);
        doc.setTextColor(194, 120, 3);
        doc.text('MIXED COGS — MANUAL REVIEW REQUIRED', MARGIN + 8, y + 12);
        y += 18;

        for (const cat of report.mixedCOGS) {
          checkPageBreak(30);
          const catTotal = (cat.items ?? []).reduce((sum, it) => sum + (it.amount ?? 0), 0);

          doc.setFillColor(232, 240, 247);
          doc.rect(MARGIN, y, CONTENT_WIDTH, 16, 'F');
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(8.5);
          doc.setTextColor(...NAVY);
          doc.text(cat.category, MARGIN + 8, y + 12);
          const mixCatStr = formatCurrency(catTotal);
          const mixCatW = doc.getTextWidth(mixCatStr);
          doc.text(mixCatStr, rightEdge - mixCatW, y + 12);
          y += 18;

          (cat.items ?? []).forEach((item, idx) => {
            checkPageBreak(16);
            if (idx % 2 === 0) {
              doc.setFillColor(249, 249, 249);
              doc.rect(MARGIN, y, CONTENT_WIDTH, 14, 'F');
            }
            const desc = item.description ?? '';
            const truncated = desc.length > 60 ? desc.substring(0, 57) + '...' : desc;
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(8);
            doc.setTextColor(...DARK);
            doc.text(`  ${item.date ?? ''}  ${truncated}`, MARGIN + 4, y + 10);
            const amtStr = formatCurrency(item.amount ?? 0);
            const amtW = doc.getTextWidth(amtStr);
            doc.text(amtStr, rightEdge - amtW, y + 10);
            y += 14;
          });

          doc.setDrawColor(...LGREY);
          doc.setLineWidth(0.3);
          doc.line(MARGIN, y, rightEdge, y);
          y += 4;
        }

        // Mixed COGS subtotal
        checkPageBreak(18);
        doc.setFillColor(255, 243, 224);
        doc.rect(MARGIN, y, CONTENT_WIDTH, 16, 'F');
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8.5);
        doc.setTextColor(194, 120, 3);
        doc.text('Mixed COGS Subtotal', MARGIN + 8, y + 12);
        const mixSubStr = formatCurrency(report.totalMixedCOGS ?? 0);
        const mixSubW = doc.getTextWidth(mixSubStr);
        doc.text(mixSubStr, rightEdge - mixSubW, y + 12);
        y += 22;
      }

      // Total COGS bar
      checkPageBreak(22);
      doc.setFillColor(...NAVY);
      doc.rect(MARGIN, y, CONTENT_WIDTH, 18, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(...WHITE);
      doc.text('Total COGS', MARGIN + 8, y + 13);
      const totalCogsStr = formatCurrency(report.totalCOGS ?? 0);
      const totalCogsW = doc.getTextWidth(totalCogsStr);
      doc.text(totalCogsStr, rightEdge - totalCogsW, y + 13);
      y += 26;

      // Gross Profit highlight
      checkPageBreak(22);
      doc.setFillColor(...LBLUE);
      doc.rect(MARGIN, y, CONTENT_WIDTH, 18, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(29, 78, 216);
      doc.text('Gross Profit', MARGIN + 8, y + 13);
      const gpStr = formatCurrency(report.grossProfit ?? 0);
      const gpW = doc.getTextWidth(gpStr);
      doc.text(gpStr, rightEdge - gpW, y + 13);
      y += 26;
    } else if (report.cogs && report.cogs.length > 0) {
      // Fallback: no taxable split available, render flat COGS
      drawSection('COST OF GOODS SOLD', report.cogs, 'Total COGS', report.totalCOGS ?? 0);

      // Gross Profit highlight
      checkPageBreak(22);
      doc.setFillColor(...LBLUE);
      doc.rect(MARGIN, y, CONTENT_WIDTH, 18, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(29, 78, 216);
      doc.text('Gross Profit', MARGIN + 8, y + 13);
      const gpStr = formatCurrency(report.grossProfit ?? 0);
      const gpW = doc.getTextWidth(gpStr);
      doc.text(gpStr, rightEdge - gpW, y + 13);
      y += 26;
    }

    // --- Operating Expenses ---
    if (report.operatingExpenses && report.operatingExpenses.length > 0) {
      drawSection(
        'OPERATING EXPENSES',
        report.operatingExpenses,
        'Total Operating Expenses',
        report.totalOpex ?? 0
      );
    }

    // --- Net Income Bar ---
    checkPageBreak(30);
    const niColor = netIncome >= 0 ? GREEN : RED;
    doc.setFillColor(...niColor);
    doc.rect(MARGIN, y, CONTENT_WIDTH, 26, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(...WHITE);
    doc.text('NET INCOME', MARGIN + 10, y + 18);
    const niStr = formatCurrency(netIncome);
    const niW = doc.getTextWidth(niStr);
    doc.text(niStr, rightEdge - niW, y + 18);
    y += 34;

    // --- Notes ---
    function drawNotes(title: string, items: string[]) {
      checkPageBreak(30);
      y += 6;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(...GREY);
      doc.text(title, MARGIN, y + 10);
      y += 16;

      doc.setFont('helvetica', 'normal');
      items.forEach((item) => {
        checkPageBreak(14);
        doc.text(`  ${item}`, MARGIN + 4, y + 10);
        y += 12;
      });
    }

    if (report.notes && report.notes.length > 0) {
      drawNotes('Notes & Flags', report.notes);
    }

    if (report.sourceDocuments && report.sourceDocuments.length > 0) {
      drawNotes('Source Documents', report.sourceDocuments);
    }

    // Final footer
    drawFooter();

    // Return as base64
    return doc.output('datauristring').split(',')[1] ?? null;
  } catch (err) {
    console.error('PDF generation failed:', err);
    return null;
  }
}
