#!/usr/bin/env python3
"""Prepares APK assets (fonts, Earth textures) and generates QuranData.java.

usage: prepare_assets.py <quran-qcf4 pkg> <inter-ui pkg> <amiri pkg> <globe-threejs pkg>
                         <earth-visualization pkg> <assets out dir> <java out dir>
"""
import glob
import json
import os
import sys

from fontTools.ttLib import TTFont
from PIL import Image

QCF, INTER, AMIRI, GLOBE, EARTHVIS, ASSETS, JAVA = sys.argv[1:8]

os.makedirs(os.path.join(ASSETS, 'fonts'), exist_ok=True)
os.makedirs(os.path.join(ASSETS, 'earth'), exist_ok=True)


def woff_to_ttf(src, dst):
    f = TTFont(src)
    f.flavor = None
    f.save(dst)


for w in ('Regular', 'Medium', 'SemiBold', 'Bold'):
    woff_to_ttf(os.path.join(INTER, 'web', 'Inter-%s.woff2' % w), os.path.join(ASSETS, 'fonts', 'Inter-%s.ttf' % w))
woff_to_ttf(os.path.join(AMIRI, 'files', 'amiri-arabic-400-normal.woff'), os.path.join(ASSETS, 'fonts', 'Amiri-Regular.ttf'))
woff_to_ttf(os.path.join(AMIRI, 'files', 'amiri-arabic-700-normal.woff'), os.path.join(ASSETS, 'fonts', 'Amiri-Bold.ttf'))

# Earth: 4K day + night lights, 2K clouds + ocean mask
Image.open(os.path.join(GLOBE, 'assets', 'earth-day-4k.jpg')).convert('RGB').save(
    os.path.join(ASSETS, 'earth', 'day.jpg'), quality=90)
Image.open(os.path.join(GLOBE, 'assets', 'earth-night-4k.jpg')).convert('RGB').save(
    os.path.join(ASSETS, 'earth', 'night.jpg'), quality=90)
Image.open(os.path.join(EARTHVIS, 'dist', 'textures', 'earth_clouds_2048x1024.jpg')).convert('RGB').save(
    os.path.join(ASSETS, 'earth', 'clouds.jpg'), quality=88)
Image.open(os.path.join(EARTHVIS, 'dist', 'textures', 'specular_map_2048x1024.jpg')).convert('RGB').resize(
    (1024, 512), Image.LANCZOS).save(os.path.join(ASSETS, 'earth', 'ocean.jpg'), quality=85)

# ------------------------------------------------------------ QuranData.java
index = json.load(open(os.path.join(QCF, 'index.json')))['chapters']
first_surah = []
for p in range(1, 605):
    page = json.load(open(os.path.join(QCF, 'pages', '%03d.json' % p)))
    first_surah.append(page['surahs'][0]['id'] if page['surahs'] else first_surah[-1])

JUZ_START = [1, 22, 42, 62, 82, 102, 121, 142, 162, 182, 201, 222, 242, 262, 282,
             302, 322, 342, 362, 382, 402, 422, 442, 462, 482, 502, 522, 542, 562, 582]


def jstr(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def jarr_str(xs):
    return '{' + ', '.join(jstr(x) for x in xs) + '}'


def jarr_int(xs):
    return '{' + ', '.join(str(x) for x in xs) + '}'


src = '''// Generated by tools/prepare_assets.py -- do not edit.
package com.quranvr.mushaf.ui;

public final class QuranData {
    private QuranData() {}

    public static final int PAGES = 604;
    public static final String[] NAME = %s;
    public static final String[] NAME_AR = %s;
    public static final int[] VERSES = %s;
    public static final int[] START_PAGE = %s;
    public static final int[] JUZ_START = %s;
    // first surah shown on each page (index 0 = page 1)
    public static final byte[] PAGE_SURAH = %s;

    public static int surahOfPage(int page) {
        if (page < 1) page = 1;
        if (page > PAGES) page = PAGES;
        return PAGE_SURAH[page - 1] & 0xff;
    }

    public static int juzOfPage(int page) {
        int j = 1;
        for (int i = 0; i < JUZ_START.length; i++) if (page >= JUZ_START[i]) j = i + 1;
        return j;
    }
}
''' % (
    jarr_str([c['name'] for c in index]),
    jarr_str([c['name_arabic'] for c in index]),
    jarr_int([c['verses_count'] for c in index]),
    jarr_int([c['pages'][0] for c in index]),
    jarr_int(JUZ_START),
    jarr_int(first_surah),
)
os.makedirs(JAVA, exist_ok=True)
with open(os.path.join(JAVA, 'QuranData.java'), 'w', encoding='utf-8') as f:
    f.write(src)
print('assets ready')
