#!/bin/bash
# Prepares the cross toolchain used by build_apk.sh on Ubuntu 24.04 without the
# Android SDK/NDK: clang/lld target aarch64-linux-android directly, using
# bionic headers from AOSP and link stubs generated by tools/gen_stubs.py.
set -euo pipefail
BUILD=${BUILD:-/opt/build}
mkdir -p "$BUILD/deps"
cd "$BUILD/deps"

sudo=""; [ "$(id -u)" != 0 ] && sudo=sudo
$sudo apt-get install -y --no-install-recommends clang lld llvm aapt apksigner zipalign android-framework-res \
  libegl-dev libgles-dev libegl-mesa0 zip openjdk-21-jdk-headless

# Bionic libc headers + symbol maps (AOSP mirror)
if [ ! -d bionic ]; then
  git clone --depth 1 --filter=blob:none --sparse https://github.com/aosp-mirror/platform_bionic.git bionic
  (cd bionic && git sparse-checkout set --no-cone libc/include libc/kernel/uapi libc/kernel/android/uapi \
     libc/libc.map.txt libm/libm.map.txt libdl/libdl.map.txt)
fi

# Khronos OpenXR loader for Android (Maven Central)
if [ ! -d xrl ]; then
  curl -sSLO https://repo1.maven.org/maven2/org/khronos/openxr/openxr_loader_for_android/1.1.63/openxr_loader_for_android-1.1.63.aar
  mkdir xrl && (cd xrl && unzip -q ../openxr_loader_for_android-1.1.63.aar)
fi

# Sysroot: bionic + kernel uapi + Khronos (GLES/EGL/KHR/OpenXR) + JNI headers
SR="$BUILD/sysroot/usr/include"
rm -rf "$BUILD/sysroot" && mkdir -p "$SR"
B=bionic/libc
cp -r $B/include/* "$SR/"
cp -r $B/kernel/uapi/linux $B/kernel/uapi/asm-generic $B/kernel/uapi/mtd $B/kernel/uapi/misc "$SR/"
cp -r $B/kernel/uapi/asm-arm64/asm "$SR/asm"
cp -r $B/kernel/android/uapi/* "$SR/" 2>/dev/null || true
cp -r /usr/include/GLES2 /usr/include/GLES3 /usr/include/EGL /usr/include/KHR "$SR/"
cp -r xrl/prefab/modules/headers/include/openxr "$SR/"
JDK=$(dirname "$(dirname "$(readlink -f "$(which javac)")")")
cp "$JDK/include/jni.h" "$JDK/include/linux/jni_md.h" "$SR/"
echo "sysroot ready at $BUILD/sysroot"
